# Generated by Django 5.1.1 on 2024-09-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(max_length=300, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="products",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price"
            ),
        ),
    ]
