# Generated by Django 5.1.1 on 2024-09-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_products_description_alter_products_precio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="precio",
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=123123, max_digits=10, verbose_name="precio"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(max_length=300, verbose_name="descripcion"),
        ),
    ]
